---
- name: Clone prysmaticlabs/prysm
  git:
    repo: "https://github.com/prysmaticlabs/prysm.git"
    dest: "{{ prysm_path }}"
    force: yes

- name: Prysm relase tags
  shell: "git tag --sort=committerdate | grep v"
  args:
    chdir: "{{ prysm_path }}"
  register: version_tags

- name: Check for latest release
  lineinfile:
    dest: "{{ latest_build_release_file }}"
    line: "{{ version_tags.stdout.split('\n')|last }}"
    create: yes
  register: release_tag

- name: Fail if nothing new
  fail:
    msg: "No new release detected!"
  when: not release_tag.changed