---
- name: Install required packages
  package:
    name:
    - qemu
    - binfmt-support
    - qemu-user-static
    state: present

- name: Remove builder (if existing)
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx rm builder"
  ignore_errors: yes

- name: Create builder
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --name builder"
  register: docker_builder

- name: Use builder
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx use builder"
  when: docker_builder.changed

- name: Inspect builder
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx inspect --bootstrap builder"
  when: docker_builder.changed

- name: Clone build repo
  git:
    repo: "https://github.com/eth2-spectrum/prysm-arm-build.git"
    dest: "{{ build_path }}"
    force: yes

- name: Login Dockerhub
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: Prysm relase tags
  shell: "git tag --sort=committerdate | grep {{ version_tag_filter }}"
  args:
    chdir: "{{ prysm_path }}"
  register: version_tags

- name: Adapting PRYSM_VERSION
  lineinfile:
    dest: "{{ build_path }}/arm64/prysm-bin/build_prysm.sh"
    regexp: "^PRYSM_VERSION="
    line: "PRYSM_VERSION={{ version_tags.stdout.split('\n')|last }}"

- name: Adapting DOCKER_REPOSITORY
  lineinfile:
    dest: "{{ build_path }}/arm64/prysm-bin/build_prysm.sh"
    regexp: "^DOCKER_REPOSITORY="
    line: "DOCKER_REPOSITORY={{ docker_repository }}"

- name: Build and push docker images
  shell: "./build_prysm.sh {{ item }}"
  args:
    chdir: "{{ build_path }}/arm64/prysm-bin"
  with_items:
  - beacon-chain
  - validator
  - slasher

- name: Add tag latest to images
  docker_image:
    name: "{{ docker_repository }}/prysm-{{ item }}-arm64:{{ version_tags.stdout.split('\n')|last }}"
    repository: "{{ docker_repository }}/prysm-{{ item }}-arm64:latest"
    force_tag: yes
    source: pull
    push: yes
  with_items:
  - beacon-chain
  - validator
  - slasher

- name: Cleanup - Remove images
  docker_image:
    state: absent
    name: "{{ docker_repository }}/prysm-{{ item }}-arm64:{{ version_tags.stdout.split('\n')|last }}"
  with_items:
  - beacon-chain
  - validator
  - slasher
