---
- name: Install required packages
  package:
    name:
    - qemu
    - binfmt-support
    - qemu-user-static
    state: present

- name: Remove builder (if existing)
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx rm builder"
  ignore_errors: yes

- name: Create builder
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --name builder"
  register: docker_builder

- name: Use builder
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx use builder"
  when: docker_builder.changed

- name: Inspect builder
  shell: "DOCKER_CLI_EXPERIMENTAL=enabled docker buildx inspect --bootstrap builder"
  when: docker_builder.changed

- name: Clone build repo
  git:
    repo: "https://github.com/eth2-spectrum/prysm-arm-build.git"
    dest: "{{ build_path }}"
    force: yes

- name: Login Dockerhub
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: Latest Prysm commit hash
  shell: "git ls-remote https://github.com/prysmaticlabs/prysm.git | grep HEAD"
  register: ls_remote

- name: Adapting COMMITHASH
  lineinfile:
    dest: "{{ build_path }}/arm64/prysm-scratch/build_prysm.sh"
    regexp: "^COMMITHASH="
    line: "COMMITHASH={{ ls_remote.stdout.split(' ')[0]|trim }}"

- name: Adapting VERSION_TAG
  lineinfile:
    dest: "{{ build_path }}/arm64/prysm-scratch/build_prysm.sh"
    regexp: "^VERSION_TAG="
    line: "VERSION_TAG=HEAD-{{ ls_remote.stdout.split(' ')[0][:6] }}"

- name: Adapting DOCKER_REPOSITORY
  lineinfile:
    dest: "{{ build_path }}/arm64/prysm-scratch/build_prysm.sh"
    regexp: "^DOCKER_REPOSITORY="
    line: "DOCKER_REPOSITORY={{ docker_repository }}"

- name: Adapting HASHDATE
  lineinfile:
    dest: "{{ build_path }}/arm64/prysm-scratch/build_prysm.sh"
    regexp: "^HASHDATE="
    line: "HASHDATE={{ ansible_date_time.date }}"

- name: Build and push docker images
  shell: "./build_prysm.sh {{ item }}"
  args:
    chdir: "{{ build_path }}/arm64/prysm-scratch"
  with_items:
  - beacon-chain
  - validator
  - slasher